### ISSUE TITLE
Fortitude of the bear

### ISSUE THREAD

**Issue by Xorm1** [ollidiemaus/AutoPotion#22]
looks like the wrong ID is being used. 
272679 is the ID I have.
I do not know how to code. other than copy pasting C++ for mods. but yeah. 
I appreciate your work here!

**Comment by ollidiemaus** [comment]
Thanks for the feedback I’ll take a look at it. Am 07.04.2023 um 00:40 schrieb Xorm1 ***@***.***>:﻿
looks like the wrong ID is being used.
272679 is the ID I have.
I do not know how to code. other than copy pasting C++ for mods. but yeah.
I appreciate your work here!

**Comment by ollidiemaus** [comment]
I fixed this in the current release.
