### ISSUE TITLE
Cooldown issues

### ISSUE THREAD

**Issue by Jcblmao** [ollidiemaus/AutoPotion#23]
hey, tend to have this problem pretty often, and I assume you are aware/get many comments about it, however I need to mention it to make sure you are aware, and if there is anything I/you can do to help fix it.
  
I tend to get an issue where one of my abilities/potion/healthstone comes off cooldown, the macro does not reset, i.e will stay on the previously used item.
  
For example, I was doing some testing now and used "Renewal" it has come back off cooldown, yet auto potion is stuck on health potion, even through the priority should be to revert back to renewal? I assume this is something to do with the update checks of the addon?

**Comment by ollidiemaus** [comment]
This is because the Addon just maintains a castsequence macro with the available stuff.
And castsequence could use a different reset condition but this would not work with potions and healtstones and spells because all have different cds.
