### ISSUE TITLE
[Feature Request] Add the option to Soulburn a healthstone as Warlock

### ISSUE THREAD

**Issue by Noodleboy0** [ollidiemaus/AutoPotion#28]
It would be very nice to be able to combine healthstone and soulburn into the all in one button. It's very strong in both PvE and PvP.

**Comment by ollidiemaus** [comment]
Hey there just for clarification this is the spell you are talking about right?
https://www.wowhead.com/spell=385899/soulburn

How does the spell work ? You just cast soulburn and then use a Healthstone directly afterwards ?

**Comment by Noodleboy0** [comment]
Yes that is the spell! You can macro soulburn to healthstone so they both cast on the same keystroke giving you the extra heal and temp hp. The general macro for it just simply this I believe. 
/cast Soulburn
/use Healthstone

**Comment by ollidiemaus** [comment]
Ah I see with how the addon currently works you would still have to press the button twice because its only using castsequence.
