### ISSUE TITLE
macro won update 

### ISSUE THREAD

**Issue by mca82** [ollidiemaus/AutoPotion#29]
On my warlock and macro wont update, 
![image](https://github.com/ollidiemaus/AutoPotion/assets/105712485/80e7e292-6038-46cc-8cd2-0bc8ed26e773)

still shows renewal from druid.

**Comment by mca82** [comment]
I just deleted macro and addon and reinstalled seemed to fix it.

**Comment by ollidiemaus** [comment]
Okay nice thanks for the comment anyways
