### ISSUE TITLE
Add RetPal's Flash of Light when talented into Light's Celerity?

### ISSUE THREAD

**Issue by jshier** [ollidiemaus/AutoPotion#34]
The Retribution Paladin spec skill Light's Celerity makes Flash of Light instant with a 6 second cool down. If you can detect that talent, I think it would make a good addition to the priority list.

**Comment by phuze** [comment]
@jshier Similar to issue https://github.com/ollidiemaus/AutoPotion/issues/35 , macros cannot be edited while in combat, so we would not be able to include active procs or abilities.

@ollidiemaus Please consider closing this one as well.

**Comment by jshier** [comment]
Thanks, makes sense.
