### ISSUE TITLE
Add ProtPal's Word of Glory when talented into Shining Light or Bastion of Light?

### ISSUE THREAD

**Issue by jshier** [ollidiemaus/AutoPotion#35]
While not as clear cut as #34, it would be useful to add the free Word of Glory's that can proc from Shining Light, when talented. ProtPal doesn't usually want to spend holy power of Word of Glory, so it doesn't necessarily belong in the list all the time, but when it's free I think it makes sense. Additionally, when talented into Bastion of Light, ProtPal gets three free WoGs or SotR when it's active, so it may make sense to add it in that case as well.

**Comment by phuze** [comment]
@jshier While an old issue, I thought I'd take the time to respond. We cannot modify macros during combat. Blizzard's `EditMacro()` function is protected, meaning it cannot be used while in combat to adjust macros based on active procs or abilities, which includes Word of Glory.

@ollidiemaus please consider marking this issue as closed.

**Comment by jshier** [comment]
Makes sense too.
