### ISSUE TITLE
Hearthseeking Health Injector?

### ISSUE THREAD

**Issue by physixtential** [ollidiemaus/AutoPotion#50]
![image](https://github.com/user-attachments/assets/27f8e3f0-06f5-4621-ad5c-025d0a40bb48)
Is there any plan to include the health injector tinker in your addon? This completely replaces using a potion most of the time for me and I can't use your addon anymore to automatically include healthstone which was really convenient. I see you've been updating the addon a lot since launch so I'm confused why this isn't added yet.

**Comment by phuze** [comment]
I'm not an engineer, so I'm unfamiliar with tinkers.
- Can tinkers be applied to any item, or only items crafted by engineers?
- If they can only be applied to crafted items, what slots can engineers craft?

I'm trying to determine which slots this item could possibly be applied to.

**Comment by physixtential** [comment]
> I'm not an engineer, so I'm unfamiliar with tinkers.
> 
> * Can tinkers be applied to any item, or only items crafted by engineers?
> * If they can only be applied to crafted items, what slots can engineers craft?
> 
> I'm trying to determine which slots this item could possibly be applied to.
> 
> **Update**: Asking in-game, it seems tinkers can only be applied to Helms, Wrists and Guns.

Tinkers are available to all but must be ordered from an engineer. They are similar to embellishments but in this case its an on use which makes whatever item slot it is on a use item.
Helm wrist gun sounds right.

**Comment by phuze** [comment]
I have submit a PR which adds support for this tinker.
When it's merged, please take a moment to test it and let me know if it works as expected.

You will be able to enable it in the options menu.

![image](https://github.com/user-attachments/assets/c9d7958d-4300-486e-9e52-5167121b4358)

**Comment by physixtential** [comment]
> I have submit a PR which adds support for this tinker. When it's merged, please take a moment to test it and let me know if it works as expected.
> 
> You will be able to enable it in the options menu.
> 
> ![image](https://private-user-images.githubusercontent.com/9218035/380517501-c9d7958d-4300-486e-9e52-5167121b4358.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNjU1ODYsIm5iZiI6MTczMDA2NTI4NiwicGF0aCI6Ii85MjE4MDM1LzM4MDUxNzUwMS1jOWQ3OTU4ZC00MzAwLTQ4NmUtOWU1Mi01MTY3MTIxYjQzNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjdUMjE0MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVkYjlhYzVmNjk3OGRjODQyM2NhOWY5MDM1MDg4Y2FmMjlkNjk2NWUzNTk0ZDkxMjQxZmRlMjZjZDc0YzcyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.D4K21Jm-fc5jzF6A8Z2DbfARU3Prg0G6lOOpfntBksk)

very nice. I'll test it asap.

**Comment by physixtential** [comment]
Unfortunately apparently I deleted my heartseeker bracers at some point so I can't test it.

**Comment by phuze** [comment]
> Unfortunately apparently I deleted my heartseeker bracers at some point so I can't test it.

![image](https://github.com/user-attachments/assets/b3af1184-4629-4315-b99e-5cef9ee62404)

**Comment by ollidiemaus** [comment]
This was done with #62 and also for other languages with #64
