### ISSUE TITLE
Add option to insert /stopcasting in the genearted macro

### ISSUE THREAD

**Issue by Jerry-Ma** [ollidiemaus/AutoPotion#54]
As a caster it is often that one needs to promptly use the potion during casting. Adding /stopcasting in the macro would make it much more useful.

**Comment by phuze** [comment]
@Jerry-Ma You're right, that would be a useful option to include. I've submit an update that will provide this option via the addon configuration. I have opted not to make this the default behavior, as not everyone may want that behavior.

After the change is merged, you'll be able to toggle it on in the options, by typing `/ap` or via the in-game AddOns options.

![image](https://github.com/user-attachments/assets/f9bdd4ae-61dd-416e-b1b9-4491572c46df)

**Comment by ollidiemaus** [comment]
This is added with #61 
I think stopcasting will come in handy.
