### ISSUE TITLE
LUA error with AutoPotion 3.7.2

### ISSUE THREAD

**Issue by fraerie** [ollidiemaus/AutoPotion#60]
3x [ADDON_ACTION_BLOCKED] AddOn 'AutoPotion' tried to call the protected function 'EditMacro()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `EditMacro'
[string "@AutoPotion/code.lua"]:249: in function `updateMacro'
[string "@AutoPotion/code.lua"]:261: in function <AutoPotion/code.lua:253>
[string "@AutoPotion/code.lua"]:273: in function <AutoPotion/code.lua:272>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by ollidiemaus** [comment]
I’ll take a loot at it of if I find the time but definitely not before next weekend. Maybe @phuze can help. I think this must happen in combat as it’s a protected call.

**Comment by Truewhisper** [comment]
Yes.  this happens in combat.

1x [ADDON_ACTION_BLOCKED] AddOn 'AutoPotion' tried to call the protected function 'EditMacro()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `EditMacro'
[string "@AutoPotion/code.lua"]:254: in function `updateMacro'
[string "@AutoPotion/code.lua"]:265: in function <AutoPotion/code.lua:257>
[string "@AutoPotion/code.lua"]:277: in function <AutoPotion/code.lua:276>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by ollidiemaus** [comment]
This should be fixed with #61
